StartupEvents.registry('item', event => {
        event.create('auric_ingot').displayName('§6§lVoltaic §b§lIngot')
    event.create('exotic_plating').displayName('Exotic Plating')
    event.create('exomechanical_core').displayName('§8§lExomechanical §4§lCore')
    event.create('solar_core').displayName('§6Solar Core')
    event.create('golem_fragment').displayName('Golem Fragment')
    event.create('radiant_gem').displayName('Radiant Gem')
    event.create('pyro_gem').displayName('Pyro Gem')
    event.create('ether_gem').displayName('Ether Gem')
    event.create('mystical_gem').displayName('Mystical Gem')
    event.create('star_of_eternity').displayName('§0Star of Eternity')
    event.create('star_of_havoc').displayName('§4Star of Havoc')
    event.create('star_of_the_cosmos').displayName('§5Star of the Cosmos')
    event.create('star_of_spectre').displayName('§bStar of Spectre')
    event.create('warden_bone').displayName('Warden Bone')
    event.create('nebulae_alloy').displayName('§9§lNebulae Alloy')
    event.create('molten_vulcanic_sheetmetal').displayName('Molten Vulcanic Sheetmetal')
    event.create('essence_of_helio').displayName('Essence of Helio')
    event.create('essence_of_blizzard').displayName('Essence of Blizzard')
    event.create('essence_of_earth').displayName('Essence of Earth')
    event.create('essence_of_rapture').displayName('Essence of Rapture')
    event.create('anti_essence').displayName('Anti Essence').rarity('UNCOMMON')
    event.create('wither_soul').displayName('Wither Soul')
    event.create('unfinished_eye_of_mech').displayName('Unfinished Eye of Mech')
    event.create('exo_prism').displayName('Exo Prism').rarity('EPIC')
    event.create('conceited_ingot').displayName('§9Conceited Ingot').rarity('EPIC')
    event.create('eldervine_ingot').displayName('§2Eldervine Ingot').rarity('RARE')
})