name = "Reign of Appa"
author = "Appa"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5802d368c71c786c14fbf9f27faed2f282f502706f460d5a5403040e4ad8326"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
