name = "Reign of Appa"
author = "Appa"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68f2d982b98602b47e568ee706d5c438f91389882f38ed5a7df4a83fee526889"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
