ServerEvents.tags('item', event => {
  event.add('terramity:netherite_tier', 'ancient_elements:frost_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:ender_steel_pickaxe')
  event.add('terramity:netherite_tier', 'enlightened_end:adamantite_pickaxe')
  event.add('terramity:netherite_tier', 'secretsofthevoid:scoria_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:aetherium_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:meteorite_pickaxe')
  event.add('terramity:netherite_tier', 'secretsofthevoid:scoria_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:void_steel_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:infernal_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:aetherium_pickaxe')
  event.add('terramity:netherite_tier', 'ancient_elements:elementinium_pickaxe')
  event.add('terramity:netherite_tier', 'enlightened_end:adamantite_pickaxe')

  event.add('terramity:plus_two_tier', 'ancient_elements:spectrillium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:hellstone_pickaxe')

  event.add('terramity:plus_one_tier', 'ancient_elements:meteorite_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:frost_pickaxe')
  event.add('terramity:plus_one_tier', 'secretsofthevoid:scoria_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:void_steel_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:infernal_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:aetherium_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:elementinium_pickaxe')
  event.add('terramity:plus_one_tier', 'enlightened_end:adamantite_pickaxe')

  event.add('terramity:plus_one_tier', 'ancient_elements:spectrillium_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:hellstone_pickaxe')

  event.add('terramity:plus_two_tier', 'ancient_elements:aetherium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:elementinium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:infernal_pickaxe')

  event.add('terramity:plus_two_tier', 'ancient_elements:endrium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:celestium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:galactrium_pickaxe')
  event.add('terramity:plus_two_tier', 'ancient_elements:aeonite_pickaxe')

  event.add('terramity:plus_three_tier', 'ancient_elements:hellstone_pickaxe')
  event.add('terramity:plus_three_tier', 'ancient_elements:spectrillium_pickaxe')
  event.add('terramity:plus_three_tier', 'ancient_elements:endrium_pickaxe')
  event.add('terramity:plus_three_tier', 'ancient_elements:celestium_pickaxe')
  event.add('terramity:plus_three_tier', 'ancient_elements:galactrium_pickaxe')
  event.add('terramity:plus_three_tier', 'ancient_elements:aeonite_pickaxe')

  event.add('terramity:plus_one_tier', 'ancient_elements:endrium_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:celestium_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:galactrium_pickaxe')
  event.add('terramity:plus_one_tier', 'ancient_elements:aeonite_pickaxe')
})