ServerEvents.tags('item', event => {
    event.add('enlightened_end:medium_radioactive', 'alexscaves:uranium')
    event.add('forge:ores/tin', 'ancient_elements:tin_ore', 'ancient_elements:deepslate_tin_ore', 'tohiro_ores:tin_deepslate_ore', 'tohiro_ores:tin_ore')
    event.add('forge:ingots/tin', 'ancient_elements:tin_ingot', 'tohiro_ores:tin_ingot')
    event.add('forge:ingots/lead', 'ancient_elements:lead_ingot')
    event.add('forge:ingots/bronze', 'orevolution:bronze_ingot')
    event.add('forge:ingots/steel', 'ancient_elements:steel_ingot', 'orevolution:steel_ingot')
    event.add('forge:ingots/titanium', 'ancient_elements:titanium_ingot', 'dungeons_and_combat:titanium_ingot')
    event.add('forge:gems/ruby', 'evenbetternether:nether_ruby', 'terramity:ruby')
    event.add('forge:raw_materials/uranium', 'enlightened_end:irradium_bar')
    event.add('forge:plates/cardboard', 'terramity:cardboard')
    event.add('forge:ingots/cobalt', 'tohiro_ores:cobalt_ingot')
    event.add('kubejs:essences', 'kubejs:essence_of_blizzard', 'kubejs:essence_of_rapture', 'kubejs:essence_of_earth', 'kubejs:essence_of_helio')
    event.add('forge:armor/leather', 'minecraft:leather_helmet', 'minecraft:leather_chestplate', 'minecraft:leather_leggings', 'minecraft:leather_boots')
    event.add('forge:armor/iron', 'minecraft:iron_helmet', 'minecraft:iron_chestplate', 'minecraft:iron_leggings', 'minecraft:iron_boots')
    event.add('forge:armor/scoria', 'secretsofthevoid:scoria_helmet', 'secretsofthevoid:scoria_chestplate', 'secretsofthevoid:scoria_leggings', 'secretsofthevoid:scoria_boots')
    event.add('forge:armor/spectrillium', 'ancient_elements:spectrillium_helmet', 'ancient_elements:spectrillium_chestplate', 'ancient_elements:spectrillium_leggings', 'ancient_elements:spectrillium_boots')
    event.add('forge:armor/celestium', 'ancient_elements:celestium_helmet', 'ancient_elements:celestium_chestplate', 'ancient_elements:celestium_leggings', 'ancient_elements:celestium_boots')
    event.add('kubejs:ovens', 'bakery:sandstone_stove', 'bakery:cobblestone_stove', 'bakery:stone_bricks_stove', 'bakery:end_stove', 'bakery:granite_stove', 'bakery:mud_stove', 'bakery:red_nether_bricks_stove', 'bakery:brick_stove', 'bakery:deepslate_stove', 'bakery:quartz_stove')
    event.add('kubejs:stoves', 'farmersdelight:stove', 'endersdelight:endstone_stove', 'nethersdelight:blackstone_stove')
    event.add('kubejs:fermented_footstuff', 'brewinandchewin:kimchi', 'brewinandchewin:jerky', 'brewinandchewin:pickled_pickles', 'brewinandchewin:kippers', 'brewinandchewin:cocoa_fudge')
    event.add('forge:armor/ethereal', 'valoria:ethereal_helmet', 'valoria:ethereal_chestplate', 'valoria:ethereal_leggings', 'valoria:ethereal_boots')
    event.add('forge:armor/auric', 'roacw:mars_boosters', 'roacw:mars_engine', 'roacw:mars_leg_guards', 'roacw:mars_visor', 'roacw:auric_ingot', 'roacw:auric_tesla_cuirass', 'roacw:auric_tesla_greaves', 'roacw:auric_tesla_leggings', 'roacw:auric_tesla_royal_helm')
    event.add('forge:ingots/auric', 'roacw:charged_auric_ingot', 'roacw:raw_auric', 'kubejs:auric_ingot')
})
